#This will create this metric in all the tiers, under this alias
metricPrefix: Custom Metrics|InformaticaPowerCenter|
#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO44/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: Server|Component:<COMPONENT_ID>|Custom Metrics|InformaticaPowerCenter|

# Informatica PowerCenter particulars
servers:
   - displayName: "InformaticaPowerCenterTest"
     host: "http://infawebservicehubdeva.devweb.bp.com/wsh/services/BatchServices/"
     port: 80
     username: "INFA_WEBSRVCHUB"
     password: "test"
     encryptedPassword: ""
     useSsl: false
     domainName: "NAGP_DOMAIN_CDEV"
     repositoryName: "NAGP_REP_CDEV"
     userNameSpace: "Native"

connection:
  socketTimeout: 5000
  connectTimeout: 2500
  sslCertCheckEnabled: false

proxy:
  uri:
  username:
  password:

# For each server you monitor, you will need a total of 1(by default) + 1(for serverMetrics) + 1(for jkMetrics) + 1(for each custom URL)

# According to the default config.yml, we have only 1 server => 1(by default) + 1(for jkMetrics) + 1 (for serverMetrics) + 1(assume one custom URL ) = 4 threads for one server.
# By default we want to support 5 servers, so it is 5 * 4 = 20 threads.

# So, please edit this value based on the your configuration.
numberOfThreads: 20

encryptionKey: